#ifndef		USR_LEDS_H
#define		USR_LEDS_H

#include <asm-generic/ioctl.h>

/* ioctrl cmd  */
#define	USR_LEDS_MAGIC		'E'

#define	SIGNAL1_LED_ON			0X01
#define	SIGNAL1_LED_OFF		0X02
#define	SIGNAL2_LED_ON			0X03
#define	SIGNAL2_LED_OFF		0X04
#define	SIGNAL3_LED_ON			0X05
#define	SIGNAL3_LED_OFF		0X06
#define	SIGNAL4_LED_ON			0X07
#define	SIGNAL4_LED_OFF		0X08
#define	NET_LED_ON				0X09
#define	NET_LED_OFF			0X0A
#define	CUSTOM_LED_ON			0X0B
#define	CUSTOM_LED_OFF			0X0C
#define	WORK_LED_ON			0X0D
#define	WORK_LED_OFF			0X0E
/* WRAP CMD */
#define	SIGNAL1_LED_ON_WRAPED			_IO(USR_LEDS_MAGIC, SIGNAL1_LED_ON)
#define	SIGNAL1_LED_OFF_WRAPED		_IO(USR_LEDS_MAGIC, SIGNAL1_LED_OFF)

#define	SIGNAL2_LED_ON_WRAPED			_IO(USR_LEDS_MAGIC, SIGNAL2_LED_ON)
#define	SIGNAL2_LED_OFF_WRAPED		_IO(USR_LEDS_MAGIC,	SIGNAL2_LED_OFF)

#define	SIGNAL3_LED_ON_WRAPED			_IO(USR_LEDS_MAGIC,	SIGNAL3_LED_ON)
#define	SIGNAL3_LED_OFF_WRAPED		_IO(USR_LEDS_MAGIC,	SIGNAL3_LED_OFF)

#define	SIGNAL4_LED_ON_WRAPED			_IO(USR_LEDS_MAGIC,	SIGNAL4_LED_ON)
#define	SIGNAL4_LED_OFF_WRAPED		_IO(USR_LEDS_MAGIC,	SIGNAL4_LED_OFF)

#define	NET_LED_ON_WRAPED				_IO(USR_LEDS_MAGIC,	NET_LED_ON)
#define	NET_LED_OFF_WRAPED				_IO(USR_LEDS_MAGIC,	NET_LED_OFF)

#define	CUSTOM_LED_ON_WRAPED			_IO(USR_LEDS_MAGIC,	CUSTOM_LED_ON)
#define	CUSTOM_LED_OFF_WRAPED			_IO(USR_LEDS_MAGIC,	CUSTOM_LED_OFF)

#define	WORK_LED_ON_WRAPED				_IO(USR_LEDS_MAGIC,	WORK_LED_ON)
#define	WORK_LED_OFF_WRAPED			_IO(USR_LEDS_MAGIC,	WORK_LED_OFF)

/* leds sort in struct usr_leds_priv XXX->leds[] */
#define	SIGNAL1_LED_LOCATION			3
#define	SIGNAL2_LED_LOCATION			2
#define	SIGNAL3_LED_LOCATION			1
#define	SIGNAL4_LED_LOCATION			0
#define	NET_LED_LOCATION				4
#define	CUSTOM_LED_LOCATION			5
#define	WORK_LED_LOCATION				6
/* LED ON/OFF */
#define	LED_LIGHTEN					1
#define	LED_QUENCH						0

#endif
